spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kafkatool
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: localhost:29092
  schema-registry-url: http://localhost:8081  # если пусто или закомментировано — raw Avro
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
